### ISSUE TITLE
I can't use node-wiring-pi in raspberry pi.

### ISSUE THREAD

**Issue by chung5072** [rsg98/wiring-pi#8]
Hello. I use the newest raspberry pi OS. 
That's release date is 19-04-08, and I installed node-js v10.15.3.(npm version is 6.4.1)
And I just install node-wiring-pi with using "npm install node-wiring-pi".
and I run my node-js code.
But I see this error-code
"Could not locate the bindings file."
I tried other modules, but other modules don't have problems.
Can you tell me how I can solve this problem?
I tried format os and reinstall npm, modules...
But that ways don't work on me

**Comment by rsg98** [comment]
Should be fixed in 1bb7963e7b615e4a9be27d0a64013dd49d998e7f

(Published as node-wiring-pi npm package 0.0.5)
